import type { Tables } from '$lib/schema/database.types';

export const backstage_participants: Tables<'live_debate_participants'>[] = [
	{
		id: '1',
		cam_available: true,
		cam_enable: true,
		cam_id: 'cam1',
		created_at: '2024-05-19T10:00:00Z',
		current_stage: 'stage1',
		debate: 'debate1',
		display_name: 'Jhon doe',
		is_debate_owner: false,
		is_kicked: false,
		mic_available: true,
		mic_enable: true,
		mic_id: 'mic1',
		screenshare_available: true,
		speaker_available: true,
		speaker_enable: true,
		speaker_id: 'speaker1',
		team: 'team1'
	},
	{
		id: '5',
		cam_available: true,
		cam_enable: true,
		cam_id: 'cam1',
		created_at: '2024-05-19T10:00:00Z',
		current_stage: 'stage1',
		debate: 'debate1',
		display_name: 'Jhon doe',
		is_debate_owner: false,
		is_kicked: false,
		mic_available: true,
		mic_enable: true,
		mic_id: 'mic1',
		screenshare_available: true,
		speaker_available: true,
		speaker_enable: true,
		speaker_id: 'speaker1',
		team: 'team1'
	},
	{
		id: '5',
		cam_available: true,
		cam_enable: true,
		cam_id: 'cam1',
		created_at: '2024-05-19T10:00:00Z',
		current_stage: 'stage1',
		debate: 'debate1',
		display_name: 'Jhon doe',
		is_debate_owner: false,
		is_kicked: false,
		mic_available: true,
		mic_enable: true,
		mic_id: 'mic1',
		screenshare_available: true,
		speaker_available: true,
		speaker_enable: true,
		speaker_id: 'speaker1',
		team: 'team1'
	},
	{
		id: '2',
		cam_available: false,
		cam_enable: false,
		cam_id: 'cam2',
		created_at: '2024-05-19T10:05:00Z',
		current_stage: 'stage2',
		debate: 'debate2',
		display_name: 'Sarah',
		is_debate_owner: true,
		is_kicked: false,
		mic_available: true,
		mic_enable: true,
		mic_id: 'mic2',
		screenshare_available: false,
		speaker_available: true,
		speaker_enable: true,
		speaker_id: 'speaker2',
		team: 'team2'
	},
	{
		id: '3',
		cam_available: true,
		cam_enable: false,
		cam_id: 'cam3',
		created_at: '2024-05-19T10:10:00Z',
		current_stage: 'stage3',
		debate: 'debate3',
		display_name: 'User Three',
		is_debate_owner: false,
		is_kicked: true,
		mic_available: true,
		mic_enable: false,
		mic_id: 'mic3',
		screenshare_available: true,
		speaker_available: false,
		speaker_enable: false,
		speaker_id: 'speaker3',
		team: 'team3'
	}
];
